# you can also specify your configuration via env variables of RACY_URL, RACY_USERNAME, etc to pass
# configuration to the racy cli
config:
***REMOVED***"
***REMOVED***"
***REMOVED***"
  gitlab:
***REMOVED***/api/v4"
***REMOVED***"
